version: "3.7"
services:
  mongo-service:
    image: "mongo:4.2.8"
    ports: ["27017:27017"]
    volumes:
      - "mongodb:/var/lib/mongodb/data"

  api-complains:
    build: .
    environment:
      - PORT=3000
    volumes:
      - .:/api-complains:delegated
      - rails_log:/api-complains/log
      - /api-complains/tmp
      - ./api-complains/storage:/rails/storage
    ports:
      - "3000:3000"
    depends_on:
      - mongo-service

volumes:
  mongodb:
  rails_log: