name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Stack
        run: docker-compose up -d
      - name: Create database
        run: docker-compose run api-complains rake db:create
      - name: Create database
        env:
          RAILS_ENV: test
        run: docker-compose run api-complains rake test