name: CI
on: [push, pull_request]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Stack
        run: docker-compose up -d
      - name: Create database
        run: docker-compose run api-complains rake db:create
      - name: Run rubocop
        run: docker-compose run api-complains rubocop -a
      - name: Run tests
        env:
          RAILS_ENV: test
        run: docker-compose run api-complains rake test
      - name: Run Skunk on Project
        run: |
          CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          if [[ "$CURRENT_BRANCH" != "master" ]]; then
            echo "Executing within branch: $CURRENT_BRANCH"
            docker-compose run api-complains skunk -b master
          else
            echo "Executing within master branch"
            docker-compose run api-complains skunk
          fi
          docker-compose run api-complains rubycritic
      - name: Upload Code Coverage
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/
      - name: Upload Ruby Critic
        uses: actions/upload-artifact@v2
        with:
          name: ruby-critic
          path: file:////api-complains/tmp/rubycritic
  Deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    needs: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Deploy To Heroku
        uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "api-complains" #Must be unique in Heroku
          heroku_email: "matheus_usales@hotmail.com"