name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Stack
        run: docker-compose up -d
      - name: Create database
        run: docker-compose run api-complains rake db:create
      - name: Run rubocop
        run: docker-compose run api-complains rubocop -a
      - name: Run tests
        env:
          RAILS_ENV: test
        run: docker-compose run api-complains rake test
      - name: Run Skunk on Project
        run: |
        CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          if [[ "$CURRENT_BRANCH" != "master" ]]; then
            docker-compose run api-complains echo "Executing within branch: $CURRENT_BRANCH"
            docker-compose run api-complains skunk -b master
          else
            docker-compose run api-complains echo "Executing within master branch"
            docker-compose run api-complains skunk
          fi
      - name: Upload Code Coverage
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage/